language: csharp
mono: none
dotnet: 2.2.0

install:
  - dotnet restore
  
script:
  - dotnet build
  - dotnet test CacheLiteSharp.Core.Tests/CacheLiteSharp.Tests.csproj
  - dotnet test CacheLiteSharp.DataStructures.Tests/CacheLiteSharp.DataStructures.Tests.csproj